## DASK

In [1]:
import dask 

import dask.dataframe as dd
import dask.array as da
import pandas as pd
import numpy as np

In [2]:
from dask.multiprocessing import get
from multiprocessing import cpu_count

nCores = cpu_count()

In [3]:
nCores

4

# Dask Arrays

In [4]:
##numpy arrays
import numpy as np
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [5]:
##dask arrays
import dask.array as da
da.arange(100, chunks=5).compute()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [6]:
x = da.arange(100, chunks=(5,))
x.visualize('dask.svg')

ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH

In [ ]:
x = da.arange(10, chunks=(5,))
x.visualize('dask.svg')

In [7]:
x.chunks

((5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5),)

### Convert NumPy array to Dask array

In [8]:
#numpy array
x = np.arange(1000)

#dask array
y = da.from_array(x, chunks=(100))

type(x), type(y)

(numpy.ndarray, dask.array.core.Array)

In [9]:
y.mean().compute()

499.5

In [10]:
x=da.arange(10, chunks=(5))
x

dask.array<arange, shape=(10,), dtype=int32, chunksize=(5,), chunktype=numpy.ndarray>

In [11]:
x.compute()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
x=da.arange(11, chunks=(5))
x.compute()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
x.chunks

((5, 5, 1),)

### Similar API

In [14]:
x=da.arange(11, chunks=(5)) #0 to 10
x.sum().compute()

55

In [15]:
x=da.arange(11, chunks=(5))
x.mean().compute()       #55/11

5.0

# Dask Dataframe

In [16]:
import dask.dataframe as dd

In [17]:
#for the sake of comparision
import pandas as pd
%time df1=pd.read_csv("C:\\Users\\HP\\OneDrive\\Desktop\\BF_train.csv")

CPU times: total: 562 ms
Wall time: 659 ms


In [18]:
import dask.dataframe as dd
%time df = dd.read_csv('C:\\Users\\HP\\OneDrive\\Desktop\\BF_train.csv')

CPU times: total: 15.6 ms
Wall time: 18.4 ms


## Similar API

In [19]:
df.dtypes

User_ID                         int64
Product_ID                     object
Gender                         object
Age                            object
Occupation                      int64
City_Category                  object
Stay_In_Current_City_Years     object
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2            float64
Product_Category_3            float64
Purchase                        int64
dtype: object

In [20]:
df.head()

User_ID Product_ID Gender   Age  Occupation City_Category  \
0  1000001  P00069042      F  0-17          10             A   
1  1000001  P00248942      F  0-17          10             A   
2  1000001  P00087842      F  0-17          10             A   
3  1000001  P00085442      F  0-17          10             A   
4  1000002  P00285442      M   55+          16             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3   
1                          2               0                   1   
2                          2               0                  12   
3                          2               0                  12   
4                         4+               0                   8   

   Product_Category_2  Product_Category_3  Purchase  
0                 NaN                 NaN      8370  
1                 6.0                14.0     15200  
2                 NaN                 NaN      1422  
3                14.0                 NaN      1057  
4                 NaN                 NaN      7969

In [21]:
df.isnull().sum().compute()

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            173638
Product_Category_3            383247
Purchase                           0
dtype: int64

In [22]:
df.Gender.value_counts().compute()

M    414259
F    135809
Name: Gender, dtype: int64

In [23]:
len(df), len(df.columns)

(550068, 12)

In [24]:
df = df.drop(['Product_ID'], axis=1)

# Data Preprocessing

In [25]:
df = dd.get_dummies(df.categorize()).compute()

In [26]:
df.head()

User_ID  Occupation  Marital_Status  Product_Category_1  \
0  1000001          10               0                   3   
1  1000001          10               0                   1   
2  1000001          10               0                  12   
3  1000001          10               0                  12   
4  1000002          16               0                   8   

   Product_Category_2  Product_Category_3  Purchase  Gender_F  Gender_M  \
0                 NaN                 NaN      8370         1         0   
1                 6.0                14.0     15200         1         0   
2                 NaN                 NaN      1422         1         0   
3                14.0                 NaN      1057         1         0   
4                 NaN                 NaN      7969         0         1   

   Age_0-17  ...  Age_36-45  Age_18-25  City_Category_A  City_Category_C  \
0         1  ...          0          0                1                0   
1         1  ...          0          0                1                0   
2         1  ...          0          0                1                0   
3         1  ...          0          0                1                0   
4         0  ...          0          0                0                1   

   City_Category_B  Stay_In_Current_City_Years_2  \
0                0                             1   
1                0                             1   
2                0                             1   
3                0                             1   
4                0                             0   

   Stay_In_Current_City_Years_4+  Stay_In_Current_City_Years_3  \
0                              0                             0   
1                              0                             0   
2                              0                             0   
3                              0                             0   
4                              1                             0   

   Stay_In_Current_City_Years_1  Stay_In_Current_City_Years_0  
0                             0                             0  
1                             0                             0  
2                             0                             0  
3                             0                             0  
4                             0                             0  

[5 rows x 24 columns]

In [27]:
df = df.fillna(value=0)

In [28]:
x = df[['Occupation', 'Marital_Status', 'Product_Category_1','Gender_F','Product_Category_2', 'Product_Category_3',
        'Gender_M', 'Age_0-17', 'Age_55+', 'Age_26-35', 'Age_46-50', 'Age_51-55', 'Age_36-45', 'Age_18-25', 
        'City_Category_A','City_Category_C', 'City_Category_B', 'Stay_In_Current_City_Years_2',
        'Stay_In_Current_City_Years_4+', 'Stay_In_Current_City_Years_3','Stay_In_Current_City_Years_1', 
        'Stay_In_Current_City_Years_0']]
y = df['Purchase']

In [29]:
pip install dask-ml

Note: you may need to restart the kernel to use updated packages.


In [30]:
from dask_ml.model_selection import train_test_split

In [31]:
X_train, X_test, y_train, y_test = train_test_split(x, y, random_state=1)

In [32]:
len(X_train), len(X_test), len(y_train), len(y_test)

(495061, 55007, 495061, 55007)

# Dask LR

In [33]:
training_x = X_train.values
training_y = y_train.values

In [34]:
testing_x = X_test.values
testing_y = y_test.values

In [35]:
import numpy as np
from sklearn.metrics import mean_squared_error

In [36]:
def rmse(preds, actuals):
    error = mean_squared_error(actuals, preds)
    rmse = np.sqrt(error)
    print(rmse)

In [ ]:
pip install dask_ml

In [37]:
from dask_ml.linear_model import LinearRegression
lr = LinearRegression(random_state=1, n_jobs=-1)
lr.fit(training_x,training_y)

LinearRegression(n_jobs=-1, random_state=1)

In [38]:
preds= lr.predict(training_x)
rmse(preds, training_y)

4624.266265525379


In [39]:
preds_test= lr.predict(testing_x)
rmse(preds_test, testing_y)

4624.036261865467
